<?php

/**
 * This is the model base class for the table "tbl_lancamento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Lancamento".
 *
 * Columns in table "tbl_lancamento" available as properties of the model,
 * followed by relations of table "tbl_lancamento" available as properties of the model.
 *
 * @property integer $id
 * @property string $descricao
 * @property string $documento
 * @property integer $categoria_id
 * @property integer $tipo
 * @property integer $status
 * @property string $data_vencimento
 * @property string $data_pagamento
 * @property string $data_cadastro
 * @property string $data_alteracao
 * @property string $valor
 * @property string $valor_pago
 * @property integer $usuario_id
 *
 * @property Usuario $usuario
 * @property Categoria $categoria
 */
abstract class BaseLancamento extends GxActiveRecord 
{

	public static function model($className=__CLASS__) 
    {
		return parent::model($className);
	}

	public function tableName() 
    {
		return 'tbl_lancamento';
	}

	public static function label($n = 1) 
    {
		return Yii::t('app', 'Lancamento|Lancamentos', $n);
	}

	public static function representingColumn() 
    {
		return 'descricao';
	}

	public function rules() 
    {
		return array(
			array('descricao, usuario_id', 'required'),
			array('categoria_id, tipo, status, usuario_id', 'numerical', 'integerOnly'=>true),
			array('descricao', 'length', 'max'=>255),
			array('documento', 'length', 'max'=>20),
			//array('valor, valor_pago', 'length', 'max'=>15),
			array('data_vencimento, data_pagamento, data_cadastro, data_alteracao', 'safe'),
			array('documento, categoria_id, tipo, status, data_vencimento, data_pagamento, data_cadastro, data_alteracao, valor, valor_pago', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, descricao, documento, categoria_id, tipo, status, data_vencimento, data_pagamento, data_cadastro, data_alteracao, valor, valor_pago, usuario_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() 
    {
		return array(
			'usuario' => array(self::BELONGS_TO, 'Usuario', 'usuario_id'),
			'categoria' => array(self::BELONGS_TO, 'Categoria', 'categoria_id'),
		);
	}

	public function pivotModels() 
    {
		return array(
		);
	}

	public function attributeLabels() 
    {
		return array(
			'id' => Yii::t('app', 'ID'),
			'descricao' => Yii::t('app', 'Descricao'),
			'documento' => Yii::t('app', 'Documento'),
			'categoria_id' => null,
			'tipo' => Yii::t('app', 'Tipo'),
			'status' => Yii::t('app', 'Status'),
			'data_vencimento' => Yii::t('app', 'Data Vencimento'),
			'data_pagamento' => Yii::t('app', 'Data Pagamento'),
			'data_cadastro' => Yii::t('app', 'Data Cadastro'),
			'data_alteracao' => Yii::t('app', 'Data Alteracao'),
			'valor' => Yii::t('app', 'Valor'),
			'valor_pago' => Yii::t('app', 'Valor Pago'),
			'usuario_id' => null,
			'usuario' => null,
			'categoria' => null,
		);
	}

	public function search() 
    {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('documento', $this->documento, true);
		$criteria->compare('categoria_id', $this->categoria_id);
		$criteria->compare('tipo', $this->tipo);
		$criteria->compare('status', $this->status);
		$criteria->compare('data_vencimento', $this->data_vencimento, true);
		$criteria->compare('data_pagamento', $this->data_pagamento, true);
		$criteria->compare('data_cadastro', $this->data_cadastro, true);
		$criteria->compare('data_alteracao', $this->data_alteracao, true);
		$criteria->compare('valor', $this->valor, true);
		$criteria->compare('valor_pago', $this->valor_pago, true);
		$criteria->compare('usuario_id', $this->usuario_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}