<?php

/**
 * This is the model base class for the table "tbl_usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuario".
 *
 * Columns in table "tbl_usuario" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $nome
 * @property string $email
 * @property string $login
 * @property string $senha
 * @property string $data_cadastro
 * @property string $data_alteracao
 *
 */
abstract class BaseUsuario extends GxActiveRecord 
{

	public static function model($className=__CLASS__) 
    {
		return parent::model($className);
	}

	public function tableName() 
    {
		return 'tbl_usuario';
	}

	public static function label($n = 1) 
{
		return Yii::t('app', 'Usuario|Usuarios', $n);
	}

	public static function representingColumn() 
    {
		return 'nome';
	}

	public function rules() 
    {
		return array(
			array('nome, email, login, senha', 'required'),
			array('nome', 'length', 'max'=>45),
			array('email', 'length', 'max'=>70),
			array('login', 'length', 'max'=>20),
			array('senha', 'length', 'max'=>80),
			array('data_cadastro, data_alteracao', 'safe'),
			array('data_cadastro, data_alteracao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nome, email, login, senha, data_cadastro, data_alteracao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() 
    {
		return array(
		);
	}

	public function pivotModels() 
    {
		return array(
		);
	}

	public function attributeLabels() 
    {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nome' => Yii::t('app', 'Nome'),
			'email' => Yii::t('app', 'Email'),
			'login' => Yii::t('app', 'Login'),
			'senha' => Yii::t('app', 'Senha'),
			'data_cadastro' => Yii::t('app', 'Data Cadastro'),
			'data_alteracao' => Yii::t('app', 'Data Alteracao'),
		);
	}

	public function search() 
    {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('login', $this->login, true);
		$criteria->compare('senha', $this->senha, true);
		$criteria->compare('data_cadastro', $this->data_cadastro, true);
		$criteria->compare('data_alteracao', $this->data_alteracao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}